//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBeneficiarios.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Curp { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<int> IdTelefono { get; set; }
        public Nullable<int> IdDireccion { get; set; }
    
        public virtual direcciones direcciones { get; set; }
        public virtual sexos sexos { get; set; }
        public virtual telefonos telefonos { get; set; }
    }
}
