//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppBeneficiarios.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionSolicitudesDBEntities : DbContext
    {
        public GestionSolicitudesDBEntities()
            : base("name=GestionSolicitudesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beneficiarios> beneficiarios { get; set; }
        public virtual DbSet<direcciones> direcciones { get; set; }
        public virtual DbSet<sexos> sexos { get; set; }
        public virtual DbSet<telefonos> telefonos { get; set; }
    }
}
